name: Build and Test Gradle Project

on:
  push:
    branches:
      - feature/github-workflow
jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project sources
#        uses: actions/checkout@v4
#
#      - name: Set up Gradle
#        uses: gradle/actions/setup-gradle@v3
#        with:
#          build-scan-publish: true
#          build-scan-term-of-use-url: 'https://gradle.com/terms-of-service'
#          build-scan-terms-of-use-agree: 'yes'
#
#      - name: Run build
#        run: ./gradlew build
#
#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#        - name: Checkout project sources
#          uses: actions/checkout@v4
#
#        - name: Set up Gradle
#          uses: gradle/actions/setup-gradle@v3
#          with:
#            build-scan-publish: true
#            build-scan-term-of-use-url: 'https://gradle.com/terms-of-service'
#            build-scan-terms-of-use-agree: 'yes'
#
#        - name: Run tests
#          run: ./gradlew test

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: run pwd
        run: pwd, ls

      - name: build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 192.168.178.73:6088/echoserve:latest
